// Mock data for ShareCart - B2B Surplus Food Marketplace
// This data simulates what would come from a backend API

export const mockCategories = [
  { id: '1', name: 'All', icon: '🏪', color: 'from-gray-500 to-gray-600' },
  { id: '2', name: 'Vegetables', icon: '🥬', color: 'from-green-500 to-emerald-600' },
  { id: '3', name: 'Fruits', icon: '🍎', color: 'from-red-500 to-rose-600' },
  { id: '4', name: 'Bakery', icon: '🍞', color: 'from-amber-500 to-orange-600' },
  { id: '5', name: 'Dairy', icon: '🥛', color: 'from-blue-400 to-indigo-500' },
  { id: '6', name: 'Grains', icon: '🌾', color: 'from-yellow-500 to-amber-600' },
  { id: '7', name: 'Prepared Foods', icon: '🍱', color: 'from-purple-500 to-violet-600' },
];

export const mockSellers = [
  {
    id: 's1',
    name: 'Fresh Farms Co.',
    type: 'Farm',
    rating: 4.9,
    totalSales: 1250,
    verified: true,
    location: 'Green Valley, CA',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400&h=400&fit=crop',
    banner: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&h=300&fit=crop',
    description: 'Organic farm fresh produce delivered daily. Specializing in surplus harvest sales.',
    joinedDate: '2024-01-15',
    responseRate: '98%',
    responseTime: '< 1 hour',
  },
  {
    id: 's2',
    name: 'City Bakery',
    type: 'Bakery',
    rating: 4.7,
    totalSales: 890,
    verified: true,
    location: 'Downtown, CA',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745a30bf?w=400&h=400&fit=crop',
    banner: 'https://images.unsplash.com/photo-1556910103-1c02745a30bf?w=800&h=300&fit=crop',
    description: 'Fresh baked goods daily. Near-expiry items at discounted prices.',
    joinedDate: '2024-03-20',
    responseRate: '95%',
    responseTime: '< 2 hours',
  },
  {
    id: 's3',
    name: 'Green Grocers',
    type: 'Grocery Store',
    rating: 4.8,
    totalSales: 2100,
    verified: true,
    location: 'Westside, CA',
    image: 'https://images.unsplash.com/photo-1542838132-92b535c33f0c?w=400&h=400&fit=crop',
    banner: 'https://images.unsplash.com/photo-1542838132-92b535c33f0c?w=800&h=300&fit=crop',
    description: 'Neighborhood grocery store committed to reducing food waste.',
    joinedDate: '2023-11-08',
    responseRate: '99%',
    responseTime: '< 30 min',
  },
  {
    id: 's4',
    name: 'Sunrise Dairy',
    type: 'Dairy Farm',
    rating: 4.6,
    totalSales: 654,
    verified: false,
    location: 'North County, CA',
    image: 'https://images.unsplash.com/photo-1528498033327-4a9a08c014b2?w=400&h=400&fit=crop',
    banner: 'https://images.unsplash.com/photo-1528498033327-4a9a08c014b2?w=800&h=300&fit=crop',
    description: 'Fresh dairy products from our farm to your table.',
    joinedDate: '2024-05-12',
    responseRate: '92%',
    responseTime: '< 3 hours',
  },
];

export const mockProducts = [
  {
    id: 'p1',
    name: 'Fresh Tomatoes',
    category: 'Vegetables',
    quantity: 25,
    unit: 'kg',
    price: 45,
    originalPrice: 80,
    sellerId: 's1',
    sellerName: 'Fresh Farms Co.',
    sellerRating: 4.9,
    verified: true,
    expiryDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Fresh vine-ripened tomatoes. Slight cosmetic imperfections but perfect quality.',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=300&fit=crop',
    condition: 'Excellent',
    storageType: 'Refrigerated',
    minOrderQuantity: 5,
    available: true,
    views: 234,
    location: 'Green Valley, CA',
  },
  {
    id: 'p2',
    name: 'Assorted Bread Loaves',
    category: 'Bakery',
    quantity: 30,
    unit: 'units',
    price: 25,
    originalPrice: 60,
    sellerId: 's2',
    sellerName: 'City Bakery',
    sellerRating: 4.7,
    verified: true,
    expiryDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Mix of sourdough, whole wheat, and white bread. Best before tomorrow.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
    condition: 'Good',
    storageType: 'Room Temperature',
    minOrderQuantity: 10,
    available: true,
    views: 189,
    location: 'Downtown, CA',
  },
  {
    id: 'p3',
    name: 'Organic Apples',
    category: 'Fruits',
    quantity: 50,
    unit: 'kg',
    price: 60,
    originalPrice: 120,
    sellerId: 's1',
    sellerName: 'Fresh Farms Co.',
    sellerRating: 4.9,
    verified: true,
    expiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Crisp organic apples. Various sizes, perfect for processing or resale.',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=300&fit=crop',
    condition: 'Excellent',
    storageType: 'Refrigerated',
    minOrderQuantity: 10,
    available: true,
    views: 312,
    location: 'Green Valley, CA',
  },
  {
    id: 'p4',
    name: 'Mixed Vegetables Box',
    category: 'Vegetables',
    quantity: 100,
    unit: 'boxes',
    price: 150,
    originalPrice: 300,
    sellerId: 's3',
    sellerName: 'Green Grocers',
    sellerRating: 4.8,
    verified: true,
    expiryDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Assorted seasonal vegetables. Perfect for restaurants or meal prep services.',
    image: 'https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?w=400&h=300&fit=crop',
    condition: 'Good',
    storageType: 'Refrigerated',
    minOrderQuantity: 5,
    available: true,
    views: 156,
    location: 'Westside, CA',
  },
  {
    id: 'p5',
    name: 'Fresh Milk',
    category: 'Dairy',
    quantity: 40,
    unit: 'liters',
    price: 80,
    originalPrice: 160,
    sellerId: 's4',
    sellerName: 'Sunrise Dairy',
    sellerRating: 4.6,
    verified: false,
    expiryDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Whole milk, pasteurized. Expiring in 2 days, perfect for processing.',
    image: 'https://images.unsplash.com/photo-1563636619-e9143d737437?w=400&h=300&fit=crop',
    condition: 'Excellent',
    storageType: 'Refrigerated',
    minOrderQuantity: 10,
    available: true,
    views: 98,
    location: 'North County, CA',
  },
  {
    id: 'p6',
    name: 'Croissants & Pastries',
    category: 'Bakery',
    quantity: 45,
    unit: 'units',
    price: 35,
    originalPrice: 90,
    sellerId: 's2',
    sellerName: 'City Bakery',
    sellerRating: 4.7,
    verified: true,
    expiryDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Assorted croissants and pastries. Freshly baked, best consumed today or tomorrow.',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&h=300&fit=crop',
    condition: 'Excellent',
    storageType: 'Room Temperature',
    minOrderQuantity: 15,
    available: true,
    views: 267,
    location: 'Downtown, CA',
  },
  {
    id: 'p7',
    name: 'Rice Bags',
    category: 'Grains',
    quantity: 200,
    unit: 'kg',
    price: 200,
    originalPrice: 400,
    sellerId: 's3',
    sellerName: 'Green Grocers',
    sellerRating: 4.8,
    verified: true,
    expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Premium basmati rice. Packaging slightly damaged but product intact.',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
    condition: 'Good',
    storageType: 'Dry Storage',
    minOrderQuantity: 50,
    available: true,
    views: 445,
    location: 'Westside, CA',
  },
  {
    id: 'p8',
    name: 'Prepared Salads',
    category: 'Prepared Foods',
    quantity: 25,
    unit: 'containers',
    price: 50,
    originalPrice: 125,
    sellerId: 's3',
    sellerName: 'Green Grocers',
    sellerRating: 4.8,
    verified: true,
    expiryDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'Fresh prepared salads. Must be sold today. Various types available.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    condition: 'Excellent',
    storageType: 'Refrigerated',
    minOrderQuantity: 10,
    available: true,
    views: 178,
    location: 'Westside, CA',
  },
];

export const mockChats = [
  {
    id: 'c1',
    participantId: 's1',
    participantName: 'Fresh Farms Co.',
    participantImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=100&h=100&fit=crop',
    lastMessage: 'Sure, we can negotiate on the price for bulk order.',
    lastMessageTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    unreadCount: 2,
    messages: [
      {
        id: 'm1',
        senderId: 'user',
        text: 'Hi! I\'m interested in the tomatoes. Can we negotiate on price?',
        timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'm2',
        senderId: 's1',
        text: 'Hello! Yes, we can discuss. What quantity are you looking at?',
        timestamp: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'm3',
        senderId: 'user',
        text: 'Looking at about 50kg if the price is right.',
        timestamp: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'm4',
        senderId: 's1',
        text: 'Sure, we can negotiate on the price for bulk order.',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'c2',
    participantId: 's2',
    participantName: 'City Bakery',
    participantImage: 'https://images.unsplash.com/photo-1556910103-1c02745a30bf?w=100&h=100&fit=crop',
    lastMessage: 'Thank you for your interest! We have fresh stock daily.',
    lastMessageTime: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    messages: [
      {
        id: 'm1',
        senderId: 'user',
        text: 'Do you have gluten-free options?',
        timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'm2',
        senderId: 's2',
        text: 'Thank you for your interest! We have fresh stock daily.',
        timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
];

// Helper function to calculate days until expiry
export const getExpiryInfo = (expiryDate) => {
  const now = new Date();
  const expiry = new Date(expiryDate);
  const diffTime = expiry - now;
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

  if (diffDays < 0) return { status: 'expired', text: 'Expired', color: 'danger' };
  if (diffDays === 0) return { status: 'urgent', text: 'Expires today', color: 'danger' };
  if (diffDays === 1) return { status: 'urgent', text: 'Expires tomorrow', color: 'danger' };
  if (diffDays <= 3) return { status: 'soon', text: `${diffDays} days left`, color: 'warning' };
  if (diffDays <= 7) return { status: 'moderate', text: `${diffDays} days left`, color: 'success' };
  return { status: 'safe', text: `${diffDays} days left`, color: 'success' };
};

// Helper function to calculate discount percentage
export const calculateDiscount = (price, originalPrice) => {
  return Math.round(((originalPrice - price) / originalPrice) * 100);
};

export default {
  mockCategories,
  mockSellers,
  mockProducts,
  mockChats,
  getExpiryInfo,
  calculateDiscount,
};
